development:
  adapter: mysql
  encoding: utf8
  database: isotope_site_development
  username: root
  password: 

test:
  adapter: sqlite3
  database: db/isotope_site_test.sqlite3
xx_test:
  adapter: sqlite3
  database: ":memory:"

production:
  adapter: mysql
  encoding: utf8
  database: isotope_site_development
  username: root
  password: 
